"""Tests for src.quantlib.eventstudy.

Two-sided throughout: a sample with no event effect must NOT be called
significant, and a sample with an injected effect must be.
"""

import numpy as np
import pandas as pd
import pytest

from src.quantlib.eventstudy import (
    DEFAULT_ESTIMATION_GAP,
    MIN_ESTIMATION_OBSERVATIONS,
    estimate_market_model,
    event_study,
)


def _panel(n_days=400, n_symbols=30, seed=0, beta=1.2, alpha=0.0002, vol=0.012):
    """Build a return frame generated by a known market model."""
    rng = np.random.default_rng(seed)
    index = pd.date_range("2020-01-01", periods=n_days, freq="B")
    market = pd.Series(rng.normal(0.0003, 0.009, n_days), index=index, name="market")
    symbols = [f"S{i:02d}" for i in range(n_symbols)]
    data = {
        s: alpha + beta * market.to_numpy() + rng.normal(0.0, vol, n_days)
        for s in symbols
    }
    return pd.DataFrame(data, index=index), market


# --- market model fitting ---


def test_market_model_recovers_known_alpha_and_beta():
    rng = np.random.default_rng(5)
    market = rng.normal(0.0, 0.01, 500)
    asset = 0.0005 + 1.4 * market + rng.normal(0.0, 0.002, 500)
    fit = estimate_market_model(asset, market)
    assert fit.beta == pytest.approx(1.4, abs=0.03)
    assert fit.alpha == pytest.approx(0.0005, abs=0.0003)
    assert fit.residual_std == pytest.approx(0.002, rel=0.15)
    assert fit.observations == 500


def test_market_adjusted_model_fixes_beta_at_one():
    rng = np.random.default_rng(6)
    market = rng.normal(0.0, 0.01, 200)
    asset = market + rng.normal(0.0, 0.001, 200)
    fit = estimate_market_model(asset, market, model="market_adjusted")
    assert fit.alpha == 0.0
    assert fit.beta == 1.0


def test_mean_adjusted_model_ignores_the_market():
    rng = np.random.default_rng(7)
    market = rng.normal(0.0, 0.01, 200)
    asset = 0.001 + rng.normal(0.0, 0.003, 200)
    fit = estimate_market_model(asset, market, model="mean_adjusted")
    assert fit.beta == 0.0
    assert fit.alpha == pytest.approx(asset.mean())


def test_short_estimation_window_is_an_error():
    with pytest.raises(ValueError, match="at least"):
        estimate_market_model(np.zeros(10), np.zeros(10))


def test_constant_market_leaves_beta_unidentified():
    rng = np.random.default_rng(8)
    with pytest.raises(ValueError, match="not identified"):
        estimate_market_model(rng.normal(0, 0.01, 100), np.zeros(100))


def test_unknown_model_rejected():
    with pytest.raises(ValueError, match="model must be one of"):
        estimate_market_model(np.zeros(100), np.zeros(100), model="cape")


# --- the null: no effect must not be called significant ---


def test_no_effect_sample_is_not_significant():
    returns, market = _panel(seed=101)
    events = [(s, returns.index[250]) for s in returns.columns]
    result = event_study(returns, market, events, event_window=(-2, 2))

    assert abs(result.caar_total) < 0.01
    assert result.bmp_p_value > 0.05
    assert result.t_p_value > 0.05


# --- an injected effect must be found, at the right size ---


def test_injected_event_day_jump_is_recovered_in_caar():
    returns, market = _panel(seed=202)
    event_row = 250
    jump = 0.05
    returns = returns.copy()
    returns.iloc[event_row] += jump

    events = [(s, returns.index[event_row]) for s in returns.columns]
    result = event_study(returns, market, events, event_window=(-2, 2))

    assert result.caar_total == pytest.approx(jump, abs=0.01)
    assert result.aar.loc[0] == pytest.approx(jump, abs=0.01)
    # Days either side of the event carry no injected effect.
    assert abs(result.aar.loc[-1]) < 0.01
    assert abs(result.aar.loc[1]) < 0.01
    assert result.bmp_p_value < 0.01
    assert result.patell_p_value < 0.01
    assert result.t_p_value < 0.01


def test_car_is_exactly_the_sum_of_the_abnormal_returns():
    returns, market = _panel(seed=303)
    events = [(s, returns.index[250]) for s in returns.columns[:5]]
    result = event_study(returns, market, events, event_window=(-3, 3))
    for outcome in result.events:
        assert outcome.car == pytest.approx(float(outcome.abnormal_returns.sum()))


def test_caar_is_the_running_sum_of_aar():
    returns, market = _panel(seed=304)
    events = [(s, returns.index[250]) for s in returns.columns]
    result = event_study(returns, market, events, event_window=(-4, 4))
    assert result.caar.to_numpy() == pytest.approx(np.cumsum(result.aar.to_numpy()))
    assert result.caar_total == pytest.approx(result.caar.iloc[-1])


# --- the estimation window must not see the event ---


def test_estimation_window_excludes_the_event_window():
    returns, market = _panel(seed=404)
    event_row = 250
    contaminated = returns.copy()
    # A violent, sustained move confined to the event window. If the estimation
    # window overlapped it, beta would be dragged and the abnormal return would
    # shrink toward zero -- the study would under-report its own finding.
    contaminated.iloc[event_row - 5 : event_row + 6] += 0.25

    events = [(s, returns.index[event_row]) for s in returns.columns]
    clean = event_study(returns, market, events, event_window=(-5, 5))
    dirty = event_study(contaminated, market, events, event_window=(-5, 5))

    # The fitted betas are unchanged: the estimation window never saw the shock.
    for a, b in zip(clean.events, dirty.events):
        assert a.fit.beta == pytest.approx(b.fit.beta, rel=1e-12)
    # And the whole injected move shows up as abnormal return: 11 days x 0.25.
    assert dirty.caar_total == pytest.approx(clean.caar_total + 11 * 0.25, abs=0.02)


def test_estimation_gap_is_respected():
    returns, market = _panel(seed=405)
    event_row = 250
    contaminated = returns.copy()
    # Poison only the gap rows, which sit between the estimation and event
    # windows and must be used by neither.
    gap_start = event_row - 5 - DEFAULT_ESTIMATION_GAP
    contaminated.iloc[gap_start : event_row - 5] += 0.30

    events = [(s, returns.index[event_row]) for s in returns.columns]
    clean = event_study(returns, market, events, event_window=(-5, 5))
    dirty = event_study(contaminated, market, events, event_window=(-5, 5))

    for a, b in zip(clean.events, dirty.events):
        assert a.fit.beta == pytest.approx(b.fit.beta, rel=1e-12)
        assert a.car == pytest.approx(b.car, rel=1e-12)


# --- BMP vs Patell under event-induced variance ---


def test_bmp_survives_event_induced_variance_where_patell_over_rejects():
    # The null is true: no mean effect. But the event window is three times as
    # volatile as the estimation window, which is what real events do. Patell
    # assumes event-window variance equals estimation-window variance and
    # therefore rejects far too often; BMP takes the cross-sectional variance of
    # the standardised values and holds its size.
    rng = np.random.default_rng(909)
    patell_rejections = 0
    bmp_rejections = 0
    trials = 60

    for trial in range(trials):
        n_days, n_symbols = 320, 40
        index = pd.date_range("2020-01-01", periods=n_days, freq="B")
        market = pd.Series(rng.normal(0.0, 0.008, n_days), index=index)
        event_row = 250
        data = {}
        for i in range(n_symbols):
            noise = rng.normal(0.0, 0.01, n_days)
            noise[event_row - 2 : event_row + 3] *= 3.0  # variance, not mean
            data[f"S{i:02d}"] = 1.0 * market.to_numpy() + noise
        frame = pd.DataFrame(data, index=index)
        events = [(s, index[event_row]) for s in frame.columns]
        result = event_study(frame, market, events, event_window=(-2, 2))
        patell_rejections += result.patell_p_value < 0.05
        bmp_rejections += result.bmp_p_value < 0.05

    patell_rate = patell_rejections / trials
    bmp_rate = bmp_rejections / trials
    assert bmp_rate <= 0.15, f"BMP should hold its size, got {bmp_rate:.2%}"
    assert patell_rate > bmp_rate, (
        f"Patell should over-reject under event-induced variance "
        f"(patell {patell_rate:.2%} vs bmp {bmp_rate:.2%})"
    )


# --- dropped events are reported, never silently skipped ---


def test_unknown_symbol_is_dropped_with_a_reason():
    returns, market = _panel(seed=505)
    events = [("S00", returns.index[250]), ("NOPE", returns.index[250])]
    result = event_study(returns, market, events)
    assert len(result.events) == 1
    assert result.dropped == (("NOPE", returns.index[250], "symbol not in returns frame"),)


def test_event_too_early_for_an_estimation_window_is_dropped():
    returns, market = _panel(seed=506)
    events = [("S00", returns.index[5])]
    with pytest.raises(ValueError, match="no event could be measured"):
        event_study(returns, market, events)


def test_event_window_running_past_the_frame_is_dropped():
    returns, market = _panel(seed=507)
    events = [("S00", returns.index[250]), ("S01", returns.index[-2])]
    result = event_study(returns, market, events, event_window=(-1, 5))
    reasons = [r for _, _, r in result.dropped]
    assert reasons == ["event window runs past the frame end"]


def test_non_finite_event_window_is_dropped():
    returns, market = _panel(seed=508)
    returns = returns.copy()
    returns.iloc[250, returns.columns.get_loc("S00")] = np.nan
    events = [("S00", returns.index[250]), ("S01", returns.index[250])]
    result = event_study(returns, market, events, event_window=(-1, 1))
    assert [s for s, _, _ in result.dropped] == ["S00"]
    assert [o.symbol for o in result.events] == ["S01"]


# --- event-date anchoring ---


def test_non_trading_event_date_anchors_to_previous_session():
    returns, market = _panel(seed=509)
    friday_pos = next(
        pos for pos in range(200, len(returns) - 1) if returns.index[pos].weekday() == 4
    )
    friday = returns.index[friday_pos]
    saturday = friday + pd.Timedelta(days=1)
    assert saturday not in returns.index

    returns = returns.copy()
    returns.iloc[friday_pos, returns.columns.get_loc("S00")] += 0.10
    returns.iloc[friday_pos + 1, returns.columns.get_loc("S00")] -= 0.20

    result = event_study(
        returns,
        market,
        [("S00", saturday)],
        event_window=(0, 0),
        model="mean_adjusted",
    )

    outcome = result.events[0]
    expected = returns.loc[friday, "S00"] - outcome.fit.alpha
    assert outcome.event_date == friday
    assert outcome.abnormal_returns.loc[0] == pytest.approx(expected)


def test_exact_event_date_remains_on_that_session():
    returns, market = _panel(seed=510)
    event_date = returns.index[250]

    result = event_study(
        returns,
        market,
        [("S00", event_date)],
        event_window=(0, 0),
    )

    assert result.events[0].event_date == event_date


def test_event_before_first_session_is_dropped():
    returns, market = _panel(seed=511)
    events = [
        ("S00", returns.index[250]),
        ("S01", returns.index[0] - pd.Timedelta(days=1)),
    ]

    result = event_study(returns, market, events)

    assert [outcome.symbol for outcome in result.events] == ["S00"]
    assert result.dropped[0][2] == "event date is before the frame starts"


def test_event_after_last_session_is_dropped():
    returns, market = _panel(seed=512)
    events = [
        ("S00", returns.index[250]),
        ("S01", returns.index[-1] + pd.Timedelta(days=1)),
    ]

    result = event_study(returns, market, events)

    assert [outcome.symbol for outcome in result.events] == ["S00"]
    assert result.dropped[0][2] == "event date is after the frame ends"


# --- clustering disclosure ---


def test_shared_event_dates_are_flagged():
    returns, market = _panel(seed=606)
    same_day = returns.index[250]
    events = [(s, same_day) for s in returns.columns[:4]]
    result = event_study(returns, market, events)
    assert result.shared_event_dates == (same_day,)


def test_distinct_event_dates_are_not_flagged():
    returns, market = _panel(seed=607)
    events = [
        ("S00", returns.index[240]),
        ("S01", returns.index[250]),
        ("S02", returns.index[260]),
    ]
    result = event_study(returns, market, events)
    assert result.shared_event_dates == ()


# --- input validation ---


def test_inverted_event_window_rejected():
    returns, market = _panel(seed=707)
    with pytest.raises(ValueError, match="start must be <= end"):
        event_study(returns, market, [("S00", returns.index[250])], event_window=(3, -3))


def test_negative_estimation_gap_rejected():
    returns, market = _panel(seed=708)
    with pytest.raises(ValueError, match="estimation_gap must be >= 0"):
        event_study(returns, market, [("S00", returns.index[250])], estimation_gap=-1)


def test_too_short_estimation_window_rejected():
    returns, market = _panel(seed=709)
    with pytest.raises(ValueError, match="estimation_window must be at least"):
        event_study(
            returns,
            market,
            [("S00", returns.index[250])],
            estimation_window=MIN_ESTIMATION_OBSERVATIONS - 1,
        )


def test_empty_events_rejected():
    returns, market = _panel(seed=710)
    with pytest.raises(ValueError, match="events is empty"):
        event_study(returns, market, [])


def test_market_missing_labels_is_an_error():
    returns, market = _panel(seed=711)
    with pytest.raises(ValueError, match="missing"):
        event_study(returns, market.iloc[10:], [("S00", returns.index[250])])


def test_post_event_only_window_is_allowed():
    returns, market = _panel(seed=712)
    events = [(s, returns.index[250]) for s in returns.columns]
    result = event_study(returns, market, events, event_window=(1, 5))
    assert result.event_window == (1, 5)
    assert list(result.aar.index) == [1, 2, 3, 4, 5]

# --- non-parametric tests (Corrado rank and Cowan sign) ---


def test_corrado_rank_and_cowan_sign_detect_positive_reaction():
    returns, market = _panel(seed=801)
    event_day = returns.index[250]
    # Inject positive abnormal returns in the event window for all assets
    returns_injected = returns.copy()
    for col in returns_injected.columns:
        returns_injected.loc[event_day, col] += 0.05

    events = [(s, event_day) for s in returns.columns]
    result = event_study(returns_injected, market, events, event_window=(0, 2))

    assert result.positive_car_fraction == pytest.approx(1.0)
    assert result.cowan_sign_z > 2.0
    assert result.cowan_sign_p_value < 0.05
    assert result.corrado_rank_z > 2.0
    assert result.corrado_rank_p_value < 0.05


def test_corrado_rank_and_cowan_sign_single_event_safe_nan():
    returns, market = _panel(seed=802)
    event_day = returns.index[250]
    events = [("S00", event_day)]
    result = event_study(returns, market, events, event_window=(0, 2))

    assert np.isnan(result.corrado_rank_z)
    assert np.isnan(result.corrado_rank_p_value)
    assert np.isnan(result.cowan_sign_z)
    assert np.isnan(result.cowan_sign_p_value)
    assert 0.0 <= result.positive_car_fraction <= 1.0


def test_corrado_rank_and_cowan_sign_tolerate_nan_in_estimation_period():
    returns, market = _panel(seed=803)
    event_day = returns.index[250]
    # Insert scattered NaNs in the pre-event estimation window
    returns.iloc[50, 0] = np.nan
    market.iloc[60] = np.nan
    events = [(s, event_day) for s in returns.columns]
    result = event_study(returns, market, events, event_window=(0, 2))
    assert np.isfinite(result.positive_car_fraction)
